 export const fieldsToExclude = [
    'referenceId',
    'sellerType',
    'Individual',
    'New',
    'Available',
    'Hot',
    'Verified',
    'Zero Km',
    'Discounted',
    'Save Ten Percent',
    'Save Twenty Percent',
    'Save Thirty Percent',
    'Save Forty Percent',
    'Save Fifty Percent',
    'Save Sixty Percent',
    'Save Seventy Percent',
    'Eid Collection',
    'New Collection',
    'Black Friday',
    'Holidays',
    'Ramadan',
    'Weekly Finds',
    'Highlights',
    'Summer',
    'Autumn'
  ];
