import { ApartmentProduct, MobileProduct } from "@/types/product";

export const carsData = [
  {
    id: 1,
    type: 'car',
    image: '/images/home/products/cars/cars1.webp',
    price: 25000,
    discountPrice: 22000,
    description: 'Jeep Grand Cherokee 2018 limited clean',
    location: 'Jnah, Beirut',
    isVerified: true,
    timePosted: '2025-12-24T10:30:00',
    mileage: 95000,
    year: 2018,
    isFavorite: false,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'White'
  },
  {
    id: 2,
    type: 'car',
    image: '/images/home/products/cars/cars3.webp',
    price: 40500,
    description: 'BMW X5 2022 - Full Options, Premium Package, Panoramic RoofJetour T2 Travel + 0 km - 8 Speed automatic - Crystal Gear',
    location: 'Dbih , meten',
    isVerified: false,
    timePosted: '2025-12-17T09:15:00',
    mileage: 0,
    year: 2022,
    isFavorite: true,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Black'
  },
  {
    id: 3,
    type: 'car',
    image: '/images/home/products/cars/cars.webp',
    price: 39000,
    // discountPrice: 32000,
    description: 'Land Rover Range Rover Sport 2019',
    location: 'Hazmieh',
    isVerified: true,
    timePosted: '2025-11-18T14:20:00',
    mileage: 95000,
    year: 2019,
    isFavorite: false,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    color: 'Silver'
  },
  {
    id: 4,
    type: 'car',
    image: '/images/home/products/cars/cars.webp',
    price: 15000,
    description: 'Land Rover Range Rover Sport 2011',
    location: 'Jamhour, Baabda',
    isVerified: true,
    timePosted: '2024-01-19T16:45:00',
    mileage: 157000,
    year: 2011,
    isFavorite: false,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Blue'
  },
  {
    id: 5,
    type: 'car',
    image: '/images/home/products/cars/cars.webp',
    price: 32000,
    discountPrice: 29000,
    description: 'Range Rover Evoque 2021 - Premium Package, Sunroof',
    location: 'Doha, Qatar',
    isVerified: true,
    timePosted: '2024-01-20T11:30:00',
    mileage: 28000,
    year: 2021,
    isFavorite: true,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Gray'
  }
]

export const apartmentsData: ApartmentProduct[] = [
  {
    id: 1,
    type: 'apartment',
    image: '/images/home/products/apartment/apartment1.webp',
    price: 35000,
    description: 'Apartment For Rent in Achrafieh -Gym & Pool- شقة للايجار في الاشرفية',
    location: 'Achrafieh',
    isVerified: true,
    timePosted: '2025-12-21T14:45:00',
    bedrooms: 3,
    sqm: 326,
    bathrooms: 5,
    isFavorite: true,
    floor: 15,
    furnished: true
  },
  {
    id: 2,
    type: 'apartment',
    image: '/images/home/products/apartment/apartment2.webp',
    price: 2500,
    discountPrice: 165000,
    description: 'Apartment for Rent in Ramleh Al-Baydaa - #R3011',
    location: 'Ramlet el Bayda , beirut',
    isVerified: true,
    timePosted: '2024-01-18T16:20:00',
    bedrooms: 2,
    sqm: 400,
    bathrooms: 4,
    isFavorite: false,
    floor: 8,
    furnished: false
  },
  {
    id: 3,
    type: 'apartment',
    image: '/images/home/products/apartment/apartment3.webp',
    price: 1200,
    description: 'bristol area hamra',
    location: 'Hamra , Beirut',
    isVerified: true,
    timePosted: '2024-01-17T11:30:00',
    bedrooms: 3,
    sqm: 210,
    bathrooms: 3,
    isFavorite: true,
    floor: 25,
    furnished: true
  },
  {
    id: 4,
    type: 'apartment',
    image: '/images/home/products/apartment/apartment4.webp',
    price: 2100,
    discountPrice: 89000,
    description: 'apartments for rent in louaizeh baabda شقق للايجار في لويزة بعبدا',
    location: 'Louaizeh, Baabda',
    isVerified: false,
    timePosted: '2025-12-17T13:15:00',
    bedrooms: 3,
    sqm: 65,
    bathrooms: 5,
    isFavorite: false,
    floor: 5,
    furnished: true
  }
];

export const mobilesData: MobileProduct[] = [
  {
    id: 1,
    type: 'mobile',
    image: '/images/home/products/mobile/phone1.webp',
    price: 1200,
    discountPrice: 1099,
    description: 'iPhone 15 Pro Max 256GB - Brand New, Sealed Box, Face ID, Dynamic Island',
    location: 'Dubai, UAE',
    isVerified: true,
    timePosted: '2025-01-16T12:15:00',
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    storage: '256GB',
    ram: '8GB',
    condition: 'New',
    isFavorite: true,
  },
  {
    id: 2,
    type: 'mobile',
    image: '/images/home/products/mobile/phone2.webp',
    price: 1030,
    discountPrice: 799,
    description: 'Samsung Galaxy S25 Ultra - 256GB Bundle Offre',
    location: 'Mar Elias , Beirut',
    isVerified: true,
    timePosted: '2025-12-21T15:30:00',
    brand: 'Samsung',
    model: 'Galaxy S25 Ultra',
    storage: '512GB',
    ram: '12GB',
    condition: 'Excellent',
    isFavorite: false,

  },
  {
    id: 3,
    type: 'mobile',
    image: '/images/home/products/mobile/phone3.webp',
    price: 740,
    description: 'Apple iPhone 16 Plus 128GB (2 Years Warranty)',
    location: 'Mar Elias , Beirut',
    isVerified: false,
    timePosted: '2025-12-19T10:45:00',
    brand: 'Google',
    model: 'Pixel 7 Pro',
    storage: '128GB',
    ram: '12GB',
    condition: 'Very Good',
    isFavorite: true
  },
  {
    id: 4,
    type: 'mobile',
    image: '/images/home/products/mobile/phone3.webp',
    price: 1100,
    discountPrice: 275,
    description: '16 pro max',
    location:'New Rawda , Metn',
    isVerified: true,
    timePosted: '2025-11-19T14:20:00',
    brand: 'Huawei',
    model: 'P60 Pro',
    storage: '256GB',
    ram: '8GB',
    condition: 'Good',
    isFavorite: false
  },
  {
    id: 5,
    type: 'mobile',
    image: '/images/home/products/mobile/phone4.webp',
    price: 720,
    description: 'Iphone 14 PRO MAX - Very Clean',
    location: 'Dekwaneh , Metn',
    isVerified: true,
    timePosted: '2025-12-22T09:15:00',
    brand: 'Xiaomi',
    model: 'Redmi Note 12',
    storage: '128GB',
    ram: '6GB',
    condition: 'New',
    isFavorite: false
  }
];